tutorial/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
     login,
     logout,
     password_reset,
     password_reset_done,
     password_reset_confirm,
     password_reset_complete
)

urlpatterns= [
url(r'^$', views.home,name='home'),
url(r'^login/$', login, {'template_name':'accounts/login.html'}, name='login'),
url(r'^logout/$', logout, {'template_name':'accounts/logout.html'}, name='logout'),
url(r'^register/$',views.register,name='register'),
url(r'^profile/$',views.view_profile,name='view_profile'),
url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
url(r'^change-password/$',views.change_password,name='change_password'),
url(r'^reset-password/$',password_reset,
{'template_name':'accounts/reset_password.html','post_reset_redirect':
'accounts:password_reset_done','email_template_name':
'accounts/reset_password_email.html'},name='reset_password'),

url(r'^reset-password/done/$',password_reset_done,{'template_name':
'accounts/reset_password_done.html'},name='password_reset_done'),

url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
password_reset_confirm,{'template_name':
'accounts/reset_password_confirm.html','post_reset_redirect':
'accounts/password_reset_complete'},name='password_reset_confirm'),

url(r'^reset-password/complete/$',password_reset_complete,{'template_name':
'accounts/reset_password_complete.html'},
name='password_reset_complete')

]

tutorial/tutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from tutorial import views

urlpatterns = [
    url(r'^$',views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/',include('accounts.urls',namespace='accounts')),
]

tutorial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

tutorial/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.http import HttpResponse


class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)

    class Meta:
        model = User
        fields={
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        }

    def save(self,commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']


        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model=User
        fields={
               'email',
               'first_name',
               'last_name',
               'password'
        }

tutorial/accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from accounts.forms import(
   RegistrationForm,
   EditProfileForm,
   )
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    numbers = [1,2,3,4,5]
    name='Anik'

    args = {'myName': name,'numbers': numbers}
    return render(request,'accounts/home.html', args)
def register(request):
    if request.method=='POST':
        form=RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))

    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request,'accounts/reg_form.html', args)

def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method=='POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form=EditProfileForm(instance=request.user)
        args={'form':form}
        return render(request,'accounts/edit_profile.html',args)

def change_password(request):
    if request.method=='POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form=PasswordChangeForm(user=request.user)
        args={'form':form}
        return render(request,'accounts/change_password.html',args)

tutorial/tutorial/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

tutorial/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}



{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button tye="submit">Submit</button>
  </form>
  <br>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}



{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button tye="submit">Submit</button>
  </form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/home.html
{% extends 'base.html' %}
<h1>Home</h1>
{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
  <h1>Home</h1>
{% endblock %}

tutorial/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container"
  <h1> Welcome </h1>
  <p>
    You can login here!!
  </p>
  <h2>
    login
  </h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container"
  <h1>
    logged out!!!
  </h1>
  <p>
    You have logged out!!
  </p>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/profile.html
{% extends 'base.html' %}



{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <h1>Profile</h1>
  <p>Username:{{ user }}</p>
  <p>First name:{{ user.first_name }}</p>
  <p>Last name:{{ user.last_name }}</p>
  <p>Email:{{ user.email }}</p>
</div>
{{ user }}
{% endblock %}

tutorial/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <h1>Register</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below,
        and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container"
  <h1> Password Reset Complete</h1>
  <a href="{% url 'accounts:login' %}">Log in</a>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container"
  <h1> Enter new Password </h1>
  <p>
    
  </p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container"
  <h1> Password Reset sent</h1>
  <p>
    We've emailed you instructions for setting your password, if an account
    exists with the email you entered. You should receive them shortly.

    If you don't receive an email, please make sure you've entered the address
    you registered with, and check your spam folder.
  </p>

</div>

{% endblock %}

tutorial/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}

	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

	{% endautoescape %}

tutorial/accounts/templates/base.html
<html>
  <head>
    <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
    integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    {% block head %}
    <title>Base</title>
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Alive Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if user.is_authenticated %}
    <ul class="nav navbar">
      <li><a href="{% url 'accounts:home' %}"> Home </a></li>
      <li><a href="{% url 'accounts:logout' %}"> Logout </a></li>
      <li><a href="{% url 'accounts:view_profile' %}"> Profile </a></li>
      <li><a href="{% url 'accounts:edit_profile' %}"> Edit Profile </a></li>
      <li><a href="{% url 'accounts:change_password' %}"> Change Password </a></li>
    </ul>
    {% else %}
    <ul class="nav navbar-nav">
     <li><a href="{% url 'accounts:reset_password' %}"> Reset Password </a></li>
    </ul>
    <ul class="nav navbar">
      <li><a href="{% url 'accounts:login' %}"> Login </a></li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:register' %}">Registration<span class="sr-only">(current)</span></a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>
    {% block body %}
       <h1>Base</h1>
     {% endblock %}
  </body>
</html>